export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const ADD_CLOCK_LIST = 'ADD_CLOCK_LIST';
export const CHANGE_Z_INDEX = 'CHANGE_Z_INDEX';
export const CHANGE_SIGNIN = 'CHANGE_SIGNIN';
export const CHANGE_CALENDER_SHOW = 'CHANGE_CALENDER_SHOW';
export const CHANGE_CALENDAR = 'CHANGE_CALENDAR';

export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';
